Save a copy in Drive of the given notebook and make changes.

Output for each of the questions is provided below each question. You need to produce the same output.

In [ ]:
import numpy as np

 1. Create a 4x6 numpy array filled with all zeros.

In [ ]:
import numpy as np
a=np.zeros((4,6), dtype=int)
print(a)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


2. Create a 5x5 numpy array filled with all ones.

In [ ]:
import numpy as np
a=np.ones((5,5), dtype = int)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


3.Create an array of (4,5) filled with 4.

In [ ]:
import numpy as np
a=np.full((4, 5), 4)
print(a)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


For questions 4-13, consider the matrix

a=[[1,2,3],[1,4,5],[8,4,2]]


4. Write a code to get print the shape of the given matrix.




In [ ]:
import numpy as np
a=np.array([[1,2,3],[1,4,5],[8,4,2]])
print(a.shape)

(3, 3)


5.Write the code to print number of elements in a.

In [ ]:
import numpy as np
a=np.array([[1,2,3],[1,4,5],[8,4,2]])
n=0
for i in np.nditer(a):
  n+=1
print(n)

9


6. Print the 2nd row,1st column and element at (1,2) of a.

In [ ]:
import numpy as np
a=np.array([[1,2,3],[1,4,5],[8,4,2]])
print(a[2,::])
print(a[::,1])
print(a[1,2])

[8 4 2]
[2 4 4]
5


7. Change the element at (2,1) to 5.

In [ ]:
import numpy as np
a=np.array([[1,2,3],[1,4,5],[8,4,2]])
a[2,1]=5
print(a)

[[1 2 3]
 [1 4 5]
 [8 5 2]]


8. Print the first and the last element of the first row using stepsize approach.

In [ ]:
import numpy as np
a=np.array([[1,2,3],[1,4,5],[8,4,2]])
print(a[0,::a.shape[1]-1])

[1 3]


9. Print the maximum and minimum values of a.

In [ ]:
import numpy as np
a=np.array([[1,2,3],[1,4,5],[8,4,2]])
max=0
min=a[0,0]
for i in np.nditer(a):
  if i<min:
    min=i
  if i>max:
    max=i
print(max)
print(min)

8
1


10. Print row-wise maximum values and their indicies of a.

In [ ]:
import numpy as np
a=np.array([[1,2,3],[1,4,5],[8,4,2]])
l=[]
li=[]
for i in a:
  n=0
  max=0
  for j in i:
    if j>max:
      max=j
      index=n
      n+=1
  l.append(max)
  li.append(index)
print(l)
print(li)

[3, 5, 8]
[2, 2, 0]


11. Divide all the elements of a by 4.

In [ ]:
import numpy as np
a=np.array([[1,2,3],[1,4,5],[8,4,2]])
a=a.astype("f")
for i in range(a.shape[0]):
  for j in range(a.shape[1]):
    a[i,j]/=4
print(a)

[[0.25 0.5  0.75]
 [0.25 1.   1.25]
 [2.   1.   0.5 ]]


12. Sort a along the second axis.

In [ ]:
import numpy as np
a=np.array([[1,2,3],[1,4,5],[8,4,2]])
for i in range(3):
  a[i]=np.sort(a[i])
print(a)

[[1 2 3]
 [1 4 5]
 [2 4 8]]


13. Print the indices that would sort a along the second axis.

In [ ]:
import numpy as np
a=np.array([[1,2,3],[1,4,5],[8,4,2]])
b=np.empty((3,3))
for i in range(3):
  b[i,np.argmin(a,axis=1)[i]] = 0
  b[i,np.argmax(a,axis=1)[i]] = 2
  for j in range(3):
    if b[i,j]!=0 and b[i,j]!=2:
      b[i,j]=1
print(b)

[[0. 1. 2.]
 [0. 1. 2.]
 [2. 1. 0.]]


14. Create an identity matrix of size 6x6.

In [ ]:
import numpy.matlib as np
print(np.identity(6, dtype=int))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


15. Let b=[1,4,3,2,6,8,5,4,2,0], split b into 3 arrays each of 3,4,3 elements.

In [ ]:
import numpy as np
b=np.array([1,4,3,2,6,8,5,4,2,0])
a=np.array([b[0:3],b[3:7],b[7:]],dtype=object)
print(a)

[array([1, 4, 3]) array([2, 6, 8, 5]) array([4, 2, 0])]


16.Create a 1-D array of 40 evenly spaced elements between 0. and 1., inclusive.

In [ ]:
import numpy as np
np.linspace(0, 1, num = 40, endpoint = True, retstep = False, dtype = float) #(from the answer given the intended number was probably 50 not 40)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

17. Mutliply given arrays element-wise.

a=[[4,7,2],[1,3,9]]

b=[[1,5,0],[2,7,5]]

In [ ]:
import numpy as np
a=np.array([[4,7,2],[1,3,9]])
b=np.array([[1,5,0],[2,7,5]])
for i in range(a.shape[0]):
  for j in range(a.shape[1]):
    a[i,j]*=b[i,j]
print(a)

[[ 4 35  0]
 [ 2 21 45]]


18. Create a 3x2 array with random values from 0 to 1.

In [ ]:
from numpy import random
x=random.rand(3,2)
print(x)

[[0.39020032 0.26559151]
 [0.77959012 0.72007938]
 [0.08098117 0.28887537]]
